### ISSUE TITLE
feat: migrate codebase from js to typescript 

### ISSUE THREAD

**Issue by 0xsudo-eth** [chiru-labs/ERC721A#103]
Typescript would offer a better development experience especially when it comes to smart contract types generated by hardhat which will allow faster and easier integration tests implementation.

I would do that if community is comfortable with typescript.

**Comment by Vectorized** [comment]
I'm a typescript noob. :(

**Comment by ahbanavi** [comment]
I agree, [typeChain ](https://github.com/dethcrypto/TypeChain) is a very useful tool, especially when it comes to writing tests.  
But let's hear others opinion on this.

**Comment by TimTinkers** [comment]
I think we should keep this reference repo as vanilla JavaScript and let users apply development tooling like TypeScript in their own forks. It makes it easier to consume this reference repo in contexts that don't have proper TypeScript tooling.

**Comment by robksawyer** [comment]
No typescript.

**Comment by IngloriousBasterd99** [comment]
No to typescript. Apply it in your own repo, if desired, and make it publicly available.

**Comment by cygaar** [comment]
My vote is on keeping it vanilla JS - I want to keep this repo as simple as possible. OZ has also kept their repo in JS and we want to try to match their setup closely.

**Comment by uranium93** [comment]
typescript can be a good addition to enhance development experience

**Comment by Austinhs** [comment]
While I like TypeScript -- Even though its really not a huge change from vanilla JS it does create a barrier between devs that use TypeScript and devs that don't use TypeScript.

IMO the mission statement for ERC721A is to create a new standard and get as much adoption of that standard as possible. Possibly pushing devs that don't use TypeScript away does not support that mission.

(Again, TypeScript is very easy addition for a normal JS dev to learn... but I know plenty of devs that just won't touch TS because they aren't familiar, they are basically scared to get into something they don't know about.)

I vote no TypeScript, and this issue should probably be closed since @cygaar basically already said they want to follow OZ as close as possible
