### ISSUE TITLE
Difference between this and ERC-1155?

### ISSUE THREAD

**Issue by Jerrywang959** [chiru-labs/ERC721A#113]
Personally, I think they are similar. Can you elaborate on the differences？

**Comment by Vectorized** [comment]
For NFTs, you would want to use ERC721, which has a `ownerOf(id)` function. 

ERC1155 doesn't have `ownerOf(id)`. 

In order to find out whether a certain account owns a certain id, 
you will need to listen to the `TransferFrom` events and record it to your own database. 

From recent twitch stream https://www.twitch.tv/videos/1299266697 by @fulldecent (36 minute mark)

**Comment by fulldecent** [comment]
Recommending to close issue and move discussion to StackOverflow or other forums.
