### ISSUE TITLE
can we use to EIP2981 Royalty with ERC721A ?

### ISSUE THREAD

**Issue by ozgurk78** [chiru-labs/ERC721A#127]
hi everyone  

We know that : ERC720 standart support the royalty standart (EIP2981) , 

but is ERC721A  support to EIP2981 Royalty ?

https://eips.ethereum.org/EIPS/eip-2981

**Comment by kyokosdream** [comment]
From my understanding, ERC721A attempts to remain as close to the original ERC721 implementation as possible. Not sure why we would want EIP2981 to be implemented in the ERC721A contract code. The proper way to do this is to create a new contract that implements both ERC721A and EIP2981.

**Comment by AboldUSER** [comment]
I used EIP2981 in the Antonym contract, which implements ERC721A. Even though I am a full supporter of EIP2981, I feel it is it's own standard and should be the choice of the dev/team if they plan to include it in their project, rather than including it directly in the ERC721A implementation.
I also recommend closing this issue.
