### ISSUE TITLE
Is it safe to use estimateGas on _safeMint function?

### ISSUE THREAD

**Issue by BatuhanK** [chiru-labs/ERC721A#147]
First of all thanks for this amazing contract (@chiru-labs and all other contributors)

According to web3.js documentation; we can estimate gas with estimateGas function. But this calculation can be misleading if a function can cost different at different contract states.

(https://web3js.readthedocs.io/en/v1.2.11/web3-eth-contract.html#methods-mymethod-estimategas)

My question is, is `_safeMint` function can consume more gas according to contract's state? (with same token count to same wallet)

**Comment by BatuhanK** [comment]
https://github.com/chiru-labs/ERC721A/blob/e03a3774699da45b63295cb843ec9152095d1fbc/contracts/ERC721A.sol#L382-L399

https://github.com/chiru-labs/ERC721A/blob/e03a3774699da45b63295cb843ec9152095d1fbc/contracts/ERC721A.sol#L411-L415

We don't allow mint from contracts, so these blocks will be executed on mint function.
I think it's safe to use estimateGas because this code blocks will consume same gas if all parameters are same.

Am I right?

**Comment by Vectorized** [comment]
Yes, it is safe. 

What the docs mean by “misleading” is that in the few seconds between estimating the gas and actually submitting the transaction, the contract state may have changed in a way that can drastically affects the gas cost of the function executed with the exact same parameters. If the actual gas cost drops, the user overpays. If the actual gas cost spikes, the user’s transaction may not get through in time. 

Pure functions will never suffer from this, as by definition, as they cannot read any state variables and their gas costs will hence be always constant. 

In practice, you don’t need to worry much about the gas cost estimate of the function being made inaccurate in the few seconds. This is because the cost to _mint and _transfer actually decreases to a plateau as the contract is being used more, with respect to the same function arguments.

**Comment by BatuhanK** [comment]
Hello @Vectorized 
> If the actual gas cost spikes, the user’s transaction may not get through in time.

I believe that is gas price not gas limit. If function made inaccurate gasEstimate and you gave that estimate to 
```
send({
        gasLimit: String(estimateGas), // <----- HERE
      })
```
Even if calculation is less than required gas, transaction will fail.
That's why I asked if it's safe to use or not.

**Comment by Vectorized** [comment]
I’m talking about the gas limit. Imagine you have a contract with bookkeeping logic that gets more expensive as more users mint. Then there is a good chance that the estimate will become too low after a few seconds, and won’t go through.
