### ISSUE TITLE
Timestamp in Ownership

### ISSUE THREAD

**Issue by AWAS666** [chiru-labs/ERC721A#15]
Why is the timestamp included in the ownership?
It seems more like an optional feature rather than a mandatory one to make the contract work.

If the point of ERC721A is to have an alternative version that saves on gas, then cutting it out seems to be the proper approach.

**Comment by AWAS666** [comment]
Same goes for numberMinted in the Addressdata btw.

**Comment by chiru-labs** [comment]
For ownership timestamp - we added this since we had extra space in the structs before hitting 32 bytes and felt like that was an appropriate place to add the data, which we plan on potentially using in the future for follow up contracts. Feel free to open a PR with the gas delta removing it though.

For numberMinted - this was actually used in the Azuki.sol derived contract to ensure that a user did not mint over X times. Note that it's slightly different from balanceOf, since balanceOf checks can be worked around by first minting some tokens, transferring those tokens out, then minting more, rinse and repeat.
