### ISSUE TITLE
Slither detected a Re-entrency attack inside ERC721A code

### ISSUE THREAD

**Issue by Tayarthouail** [chiru-labs/ERC721A#230]
I'm using ERC721A implementations, When I run slither to test it out I got a message 

"Reentrancy in ERC721A._mint(address,uint256,bytes,bool) (contracts\contract.sol#1137-1179):

the code below for 1137-1179.

[function _mint(
        address to,
        uint256 quantity,
        bytes memory _data,
        bool safe
    ) internal {
        uint256 startTokenId = _currentIndex;
        if (to == address(0)) revert MintToZeroAddress();
        if (quantity == 0) revert MintZeroQuantity();

        _beforeTokenTransfers(address(0), to, startTokenId, quantity);

        // Overflows are incredibly unrealistic.
        // balance or numberMinted overflow if current value of either + quantity > 1.8e19 (2**64) - 1
        // updatedIndex overflows if _currentIndex + quantity > 1.2e77 (2**256) - 1
        unchecked {
            _addressData[to].balance += uint64(quantity);
            _addressData[to].numberMinted += uint64(quantity);

            _ownerships[startTokenId].addr = to;
            _ownerships[startTokenId].startTimestamp = uint64(block.timestamp);

            uint256 updatedIndex = startTokenId;
            uint256 end = updatedIndex + quantity;

            if (safe && to.isContract()) {
                do {
                    emit Transfer(address(0), to, updatedIndex);
                    if (!_checkContractOnERC721Received(address(0), to, updatedIndex++, _data)) {
                        revert TransferToNonERC721ReceiverImplementer();
                    }
                } while (updatedIndex != end);
                // Reentrancy protection
                if (_currentIndex != startTokenId) revert();
            } else {
                do {
                    emit Transfer(address(0), to, updatedIndex++);
                } while (updatedIndex != end);
            }
            _currentIndex = updatedIndex;
        }
        _afterTokenTransfers(address(0), to, startTokenId, quantity);
    }](url)

**Comment by Vectorized** [comment]
Slither uses a heuristic that checks that no storage variables can be modified in a reentrant call. 

The code checks for reentrancy and reverts in the middle of the function body, which leads to a false positive. It allows the reentrant call to modify storage variables, but reverts on the parent call if a modification is detected. 

Suppose someone does a reentrant attack:

- `_mint` must be called with a non zero quantity so that it does not revert.
- After the recursive call returns, `_currentIndex` must be increased.
- The line checking that `_currentIndex` != `startTokenId` evaluates to `true`, and reverts.
